# Generated by Django 5.2.13 on 2026-05-06 22:55

import django.utils.timezone
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenteproductos',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componenteproductos',
            name='imagen',
            field=models.ImageField(blank=True, default='default/imagen.png', null=True, upload_to=productos.models.imagen_upload_to, verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='componenteproductos',
            name='sku',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
